# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54a71acd9017eedb93bae1f1cfd278f3b4335c86690ae6649e528a5b3977b35f35634f96fbb3b0da685fbdb029d244ed05ff33aa8396427e679f2c0d3c9dae18

test:
  secret_key_base: 10d0b1115b2d3831d4703a3e1d89c4599c8b45b28c9b9c0a3787a554f99117bf7e37c3c29c1a06f5f5d48c42782517f159738f83d4bbe120e4b2185200e5aafc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
